#' My Palette
#'
#' Just a palette opf colors that I like
#'
pal <- c("#b6174b", "#5398be", "#ffc914", "#23395b", "#519872")


#' Subset by Concept
#'
#' Subset OpenAlex table by concepts
#'
#' Takes in a tabl generated by an oa_fetch call and subsets
#' it by the concept you specify
#'
#' @examples
#' subset_by_concept(df, "Sociology", 0.5)
#'
#'
subset_by_concept <- function(df, concept, threshold) {

  if ("x_concepts" %in% colnames(df)) {
    df <- df |>
      rename(article_name = display_name, article_id = id) |>
      unnest(x_concepts) |>
      filter(display_name == concept & score > threshold * 100) |>
      nest(data = c(id, wikidata, display_name, level, score)) |>
      rename(x_concepts = data) |>
      rename(display_name = article_name, id = article_id)
  } else {
    df <- df |>
      rename(article_name = display_name, article_id = id) |>
      unnest(concepts) |>
      filter(display_name == concept & score > threshold) |>
      nest(data = c(id, wikidata, display_name, level, score)) |>
      rename(concepts = data) |>
      rename(display_name = article_name, id = article_id)
  }

  return(df)

}

#' Calculate Impact Factor
#'
#' Calculates the impact factor for a journal for a given year.
#'
#'
calc_if <- function(citations, articles_n) {
  return(citations / articles_n)
}


#' Calculate Productivity Score
#'
#' Calculates the "productivity score" for a given scholar
#'
#' This is the novel measure that I am exploring and is defined as
#' the sum of the citations that the scholar has recievced on their
#' articles multipled by the impact factors those articles appear in
#' over the number of articles that the scholar has published.
#'
#' @param citation_vec Vector. The vector of citations received by each
#'    article publised by the scholar.
#' @param journal_if_vec Vector. The vector of impact factors for the
#'    corresponding journals that the articles have appeared in.
#'
#' @return A single numeric value
#'
calc_productivity <- function(citation_vec, journal_if_vec) {
  return(sum(citation_vec *  journal_if_vec) / length(citation_vec))
}


#' Fetch Journal Info and Calculate Impact Factor
#'
#' Fetches article level information from a specified journal
#'    and calculates the impact factor for that journal for that
#'    year.
#'
#' @param year Numeric. The year to calculate the impact factor for
#' @param source_id string. The OpenAlex venue ID.
#'
#' @return a single numeric value
#' 
fetch_and_calculate_if <- function(year, source_id) {

  df_y_1_2 <- oa_fetch(
  entity = "works",
  locations.source.id = source_id,
  from_publication_date = paste0(year - 2, "-01-01"),
  to_publication_date = paste0(year - 1, "-12-31"),
  type = "article",  # restrict to citable items
  verbose = TRUE
  )

  # citations received in 2025 to those articles
  citation_count <- df_y_1_2 %>%
    unnest(counts_by_year, names_sep = "_") %>%
    filter(counts_by_year_year == year) %>%
    summarise(total = sum(counts_by_year_cited_by_count, na.rm = TRUE)) %>%
    pull(total)

  # denominator: citable items in 2023-2024
  n_articles <- nrow(df_y_1_2)

  impact_factor <- calc_if(citation_count, n_articles)

  return(impact_factor)

}